Prod/NSWP01/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('empty/', views.cart_empty, name='cart_empty'),
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

Prod/NSWP01/shop/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('product_list/', views.product_list, name='product_list'),
    path('mens_list/', views.mens_list, name='mens_list'),
    path('womens_list/', views.womens_list, name='womens_list'),
    path('kids_list/', views.kids_list, name='kids_list'),
    path('search_list/', views.search_list, name='search_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('django.contrib.auth.urls')),
]

Prod/NSWP01/shop/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                           args=[self.id, self.slug])

Prod/NSWP01/shop/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    """View function for home page of site."""
    num_products = Product.objects.all().count()
    num_categories = Category.objects.all().count()

    context = {
        'num_products': num_products,
        'num_categories': num_categories,
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'shop/product/index.html', context=context)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/product_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def mens_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(name__istartswith = "Men's")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/mens_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def womens_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(name__icontains = "Women's")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/womens_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def kids_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(name__icontains = "Kids'")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/kids_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def search_list(request):
    if request.GET.get('query'):
        search_slug = request.GET.get('query')
        products = Product.objects.filter(Q(name__startswith=search_slug) | Q(name__icontains=search_slug))
        products = products.order_by('name')
        return render(request, 'shop/product/search_list.html', {'products': products})
    products = Product.objects.filter(available=True)
    return render(request, 'shop/product/search_list.html', {'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product


class ProductCategoryView(LoginRequiredMixin, generic.ListView):
    model = Category

Prod/NSWP01/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">${{ product.price }}</p>

    <form action="{% url "cart:cart_add" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}
  </div>

    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}

Prod/NSWP01/shop/templates/shop/product/index.html
{% extends 'shop/base.html' %}

{% block content %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
<style>
/* width */
::-webkit-scrollbar {
  width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
  background: #f1f1f1;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #888;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #555;
}
</style>

    <h1>Home</h1>
    <img src="https://i.pinimg.com/564x/81/2f/fd/812ffda1b7401b52ecd12e894b3edb2e.jpg" height="300" width="300" class="logo">
    <h3>Brands</h3>
    <div class="row">
        <a href="/nike/">
            <img src="https://1000logos.net/wp-content/uploads/2021/11/Nike-Logo-768x432.png" height="100" width="100">
        </a>
        <a href="/adidas/">
            <img src="https://1000logos.net/wp-content/uploads/2016/10/Adidas-logo-1024x681.png" height="100" width="100">
        </a>
        <a href="/converse/">
            <img src="https://1000logos.net/wp-content/uploads/2019/12/Chuck-Taylor-All-Star-Logo.png" height="100" width="100">
        </a>
        <a href="/jordan/">
            <img src="https://1000logos.net/wp-content/uploads/2021/05/Air-Jordan-Jumpman-logo-768x432.png" height="100" width="100">
        </a>
        <a href="/vans/">
            <img src="https://1000logos.net/wp-content/uploads/2017/06/Vans-logo-1024x576.png" height="100" width="100">
        </a>
    </div>
    <br>
{#    <div class="container">#}
{#        <h4 class="text-sm-left">Leave A Comment</h4>#}
{#    </div>#}
{#        <div class="col-md-3">#}
{#            <form>#}
{#                <fieldset class="form-group">#}
{#                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">#}
{#                </fieldset>#}
{#                <fieldset class="form-group">#}
{#                    <textarea class="form-control" id="exampleMessage" placeholder="Message"></textarea>#}
{#                </fieldset>#}
{#                <fieldset class="form-group text-xs-left">#}
{#                    <button type="button" class="btn btn-secondary-outline btn-md">Send</button>#}
{#                </fieldset>#}
{#            </form>#}
{#        </div>#}
<!-- credits: https://www.codeply.com/p/EJd6H4Ejyi -->
{% endblock %}

Prod/NSWP01/shop/templates/shop/product/kids_list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
{#  <div id="sidebar">#}
{#    <h3>Categories</h3>#}
{#    <ul>#}
{#      <li {% if not category %}class="selected"{% endif %}>#}
{#        <a href="{% url "shop:kids_list" %}">All</a>#}
{#      </li>#}
{#      {% for c in categories %}#}
{#        <li {% if category.slug == c.slug %}class="selected"{% endif %}>#}
{#          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>#}
{#        </li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  </div>#}
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}All Kids' Products{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>

{% endblock %}

Prod/NSWP01/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
    <div class="dropdown">
        <button class="dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filter</button>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
                <a class="dropdown-item" href="#">Price: Low to High</a>
                <a class="dropdown-item" href="#">Price: High to Low</a>
                <a class="dropdown-item" href="#">Newest Arrivals</a>
                <a class="dropdown-item" href="#">Customer Ratings</a>
            </div>
    </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>

{% endblock %}

Prod/NSWP01/shop/templates/shop/product/mens_list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
{#  <div id="sidebar">#}
{#    <h3>Categories</h3>#}
{#    <ul>#}
{#      <li {% if not category %}class="selected"{% endif %}>#}
{#        <a href="{% url "shop:mens_list" %}">All</a>#}
{#      </li>#}
{#      {% for c in categories %}#}
{#        <li {% if category.slug == c.slug %}class="selected"{% endif %}>#}
{#          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>#}
{#        </li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  </div>#}
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}All Men's Products{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>

{% endblock %}

Prod/NSWP01/shop/templates/shop/product/product_list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:product_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
{#    <div class="header-bottom-set dropdown">#}
{#        <button class="dropdown-toggle header-action-btn" href='#' data-toggle="dropdown"><strong>Sort By: </strong></button>#}
{#            <div class="dropdown-menu" aria-labelledby="dropdown03">#}
{#                <li class="filter"><a class="dropdown-item" href="?sort=best">Best Sellers</a></li>#}
{#                <li class="filter"><a class="dropdown-item" href="?sort=new">New Arrivals</a></li>#}
{#                <li class="filter"><a class="dropdown-item" href="?sort=l2h">Price (Low to High)</a></li>#}
{#                <li class="filter"><a class="dropdown-item" href="?sort=h2l">Price (High to Low)</a></li>#}
{#            </div>#}
{#    </div>#}
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>

{% endblock %}

Prod/NSWP01/shop/templates/shop/product/search_list.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Search Results{% endif %}</h1>
    {% if products %}
      {% for product in products %}
        <div class="item">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          ${{ product.price }}
        </div>
      {% endfor %}
    {% else %}
      <p>No results found.</p>
    {% endif %}
  </div>
{% endblock %}

Prod/NSWP01/shop/templates/shop/product/womens_list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
{#  <div id="sidebar">#}
{#    <h3>Categories</h3>#}
{#    <ul>#}
{#      <li {% if not category %}class="selected"{% endif %}>#}
{#        <a href="{% url "shop:womens_list" %}">All</a>#}
{#      </li>#}
{#      {% for c in categories %}#}
{#        <li {% if category.slug == c.slug %}class="selected"{% endif %}>#}
{#          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>#}
{#        </li>#}
{#      {% endfor %}#}
{#    </ul>#}
{#  </div>#}
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}All Women's Products{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
        ${{ product.price }}
      </div>
    {% endfor %}
  </div>

{% endblock %}