Prod/NSWP01/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('empty/', views.cart_empty, name='cart_empty'),
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

Prod/NSWP01/shop/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('product_list/', views.product_list, name='product_list'),
    path('mens_list/', views.mens_list, name='mens_list'),
    path('womens_list/', views.womens_list, name='womens_list'),
    path('kids_list/', views.kids_list, name='kids_list'),
    path('search_list/', views.search_list, name='search_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('django.contrib.auth.urls')),
]

Prod/NSWP01/shop/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                           args=[self.id, self.slug])

Prod/NSWP01/shop/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    """View function for home page of site."""
    num_products = Product.objects.all().count()
    num_categories = Category.objects.all().count()

    context = {
        'num_products': num_products,
        'num_categories': num_categories,
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'shop/product/index.html', context=context)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/product_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def mens_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(name__istartswith = "Men's")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/mens_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def womens_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(name__icontains = "Women's")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/womens_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def kids_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(name__icontains = "Kids'")
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/kids_list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def search_list(request):
    if request.GET.get('query'):
        search_slug = request.GET.get('query')
        products = Product.objects.filter(Q(name__startswith=search_slug) | Q(name__icontains=search_slug))
        products = products.order_by('name')
        return render(request, 'shop/product/search_list.html', {'products': products})
    products = Product.objects.filter(available=True)
    return render(request, 'shop/product/search_list.html', {'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product


class ProductCategoryView(LoginRequiredMixin, generic.ListView):
    model = Category

Prod/NSWP01/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}NSPW{% endblock %}</title>
  <link href="{% static "css/base.css" %}" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"/>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark p-3" >
      <a class="navbar-brand" href="{% url 'shop:index' %}">NSPW</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'shop:index' %}">Home<span class="sr-only">(current)</span></a>
          </li>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Products</a>
            <div class="dropdown-menu" aria-labelledby="dropdown03">
              <a class="dropdown-item" href="{% url 'shop:product_list' %}">All</a>
              <a class="dropdown-item" href="/adidas/">Adidas</a>
              <a class="dropdown-item" href="/converse/">Converse</a>
              <a class="dropdown-item" href="/jordan/">Jordan's</a>
              <a class="dropdown-item" href="/nike/">Nike</a>
              <a class="dropdown-item" href="/vans/">Vans</a>
            </div>
          </li>
            <a class="nav-link" href="{% url 'shop:mens_list' %}">Men's<span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'shop:womens_list' %}">Women's<span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'shop:kids_list' %}">Kids'<span class="sr-only">(current)</span></a>
{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Men's</a>#}
{#            <div class="dropdown-menu" aria-labelledby="dropdown03">#}
{#              <a class="dropdown-item" href="{% url 'shop:mens_list' %}">All</a>#}
{#              <a class="dropdown-item" href="/adidas/">Adidas</a>#}
{#              <a class="dropdown-item" href="/converse/">Converse</a>#}
{#              <a class="dropdown-item" href="/jordan/">Jordan's</a>#}
{#              <a class="dropdown-item" href="/nike/">Nike</a>#}
{#              <a class="dropdown-item" href="/vans/">Vans</a>#}
{#            </div>#}
{#          </li>#}
{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Women's</a>#}
{#            <div class="dropdown-menu" aria-labelledby="dropdown03">#}
{#              <a class="dropdown-item" href="{% url 'shop:womens_list' %}">All</a>#}
{#              <a class="dropdown-item" href="/adidas/">Adidas</a>#}
{#              <a class="dropdown-item" href="/converse/">Converse</a>#}
{#              <a class="dropdown-item" href="/jordan/">Jordan's</a>#}
{#              <a class="dropdown-item" href="/nike/">Nike</a>#}
{#              <a class="dropdown-item" href="/vans/">Vans</a>#}
{#            </div>#}
{#          </li>#}
{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Kids'</a>#}
{#            <div class="dropdown-menu" aria-labelledby="dropdown03">#}
{#              <a class="dropdown-item" href="{% url 'shop:kids_list' %}">All</a>#}
{#              <a class="dropdown-item" href="/adidas/">Adidas</a>#}
{#              <a class="dropdown-item" href="/converse/">Converse</a>#}
{#              <a class="dropdown-item" href="/jordan/">Jordan's</a>#}
{#              <a class="dropdown-item" href="/nike/">Nike</a>#}
{#              <a class="dropdown-item" href="/vans/">Vans</a>#}
{#            </div>#}

            <li class="nav-item active">
          </li>
        <form class="navbar-form navbar-right" method="GET" action="{% url 'shop:search_list' %}">
            <div class="form-group m-0 d-flex">
                <input id="search-bar" type="text" class="form-control" placeholder="Search" name="query" value="{{ search_slug }}">
                <button type="submit" class="btn ml-3 btn-outline-secondary">Submit</button>
            </div>
        </form>
        </ul>
           <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a>
                </li>
            {% else %}
                <li>
                    <a class="nav-link" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span>Sign Up</a>
                </li>
            {% endif %}
        </ul>
           <ul class="nav navbar-nav">
          <a class="nav-link" href="#">
               {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart:
                        <a href="{% url "cart:cart_detail" %}">
                            {{ total_items }} item{{ total_items|pluralize }},
                            ${{ cart.get_total_price }}
                        </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
          </a>
        </ul>
    </ul>
      </div>
    </nav>
 <div class="container">
      {% if user.is_authenticated %}
        Welcome, {{ user.first_name }} {{ user.last_name }}
      {% endif %}
  </div>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
    <footer class="footer">
    <div>
        Copyright NSPW SP2023
    </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>